run:
  skip-files:
    # because we're skipping TLS verification - for now
    - cmd/entrypoints/serve.go
    - pkg/async/messages/sqs.go
    - gen

linters:
  disable-all: true
  enable:
    - errcheck
    - gas
    - gci
    - goconst
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unused
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/flyteorg)
    skip-generated: true
