apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: artifact-service
  name: artifact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifact-service
  template:
    metadata:
      labels:
        app: artifact-service
    spec:
      containers:
        - name: main
          image: ghcr.io/unionai/artifacts:sandbox
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@flyte-sandbox-postgresql.flyte:5432/postgres
            - name: REDIS_HOST
              value: flyte-sandbox-redis-headless.flyte.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: grpc
              containerPort: 50051
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: grpc
          readinessProbe:
            tcpSocket:
              port: grpc
