apiVersion: v1
kind: Service
metadata:
  name: artifact-service
  labels:
    app: artifact-service
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: artifact-service
  type: ClusterIP
